-- Generated by meta-package-manager (mpm) to enforce a supply-chain release-age
-- cooldown on yay. mpm points yay at this file through a private XDG_CONFIG_HOME.
-- The only per-run input is the MPM_COOLDOWN_EPOCH environment variable: the
-- oldest last_modified (in Unix seconds) a release may carry: now - cooldown.
local cutoff = tonumber(os.getenv("MPM_COOLDOWN_EPOCH"))

-- Chain the user's real init.lua so their yay.opt settings and hooks survive the
-- XDG_CONFIG_HOME redirect. package.path is repointed at their config dir first so
-- their own require() calls keep resolving.
local user_dir = os.getenv("MPM_YAY_USER_DIR")
if user_dir and user_dir ~= "" then
  package.path = user_dir .. "/?.lua;" .. user_dir .. "/?/init.lua;" .. package.path
  local user_init = user_dir .. "/init.lua"
  local handle = io.open(user_init, "r")
  if handle then
    handle:close()
    local ok, err = pcall(dofile, user_init)
    if not ok then
      yay.log.error("mpm cooldown: user init.lua failed: " .. tostring(err))
    end
  end
end

if cutoff then
  -- Upgrades (yay -Syu): pre-exclude AUR packages still inside the cooldown window.
  -- Exclude lists from multiple UpgradeSelect hooks are unioned, so this composes
  -- with any hook the user's own init.lua registered.
  yay.create_autocmd("UpgradeSelect", {
    desc = "mpm cooldown: hold back AUR upgrades newer than the release-age floor",
    callback = function(event)
      local exclude = {}
      for _, pkg in ipairs(event.data.upgrades) do
        if pkg.repository == "aur" and pkg.last_modified >= cutoff then
          yay.log.info("mpm cooldown: holding back " .. pkg.name)
          table.insert(exclude, pkg.name)
        end
      end
      return { exclude = exclude }
    end,
  })

  -- Installs (yay -S, which UpgradeSelect never sees): abort the transaction when an
  -- AUR base is younger than the floor. Coarser than the per-package upgrade
  -- exclusion since it stops the whole invocation, which suits mpm driving one
  -- package per call.
  yay.create_autocmd("AURPreInstall", {
    desc = "mpm cooldown: block AUR installs newer than the release-age floor",
    callback = function(event)
      if event.data.last_modified and event.data.last_modified >= cutoff then
        yay.abort(
          "mpm cooldown: " .. event.match .. " is newer than the release-age floor"
        )
      end
    end,
  })
end
