pacman:
  image: archlinux
  script:
    - pacman -Sy --noconfirm python-pip
    - python -m pip install poetry
    - poetry install
    - python -m pip install .
    - mpm --pacman -v DEBUG install vim
