# ref: https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml

# XXX One day we might move this config directly into pyproject.toml:
# https://github.com/lycheeverse/lychee/issues/1930

exclude = [
    # GitHub renders issue comments with JavaScript, so the linkcheck builder cannot find them.
    "^https://github.com/.+#issuecomment-\\d+$",
    # Skip suggesting redirecting generic download links to their binary artefact.
    "^https://github.com/.+/releases/.+/download/.*$",
    # Allow redirects of generic DOI URLs to their specific Zenodo release page.
    "^https://doi.org/.+/zenodo.*$",
    # Allow redirects to the official pip documentation.
    "^https://pip.pypa.io/.*$",
]
