name: Bug report
description: Create a report to help solving `mpm` issue
labels: ["ðŸ› bug"]
body:

  - type: markdown
    attributes:
      value: >
        Before filling this bug report, try to isolate the issue by targetting only one manager, by running `mpm` with
        a single `--<manager_id>`/`--manager <manager_id>` option.


        Once isolated to a specific manager, run `mpm --show-params` to make sure the CLI is run under a sane
        configuration and environment.


        Also run `mpm --verbosity DEBUG --all-managers managers` to check if, and how, `mpm` properly detects all
        package managers.


        Try to run your problematic command with the `--verbosity DEBUG` option. Most issues are self-explanatory and
        can be solved by looking at the verbosiest logs. One thing to look for is the all the CLI `mpm` is executing
        under the hood. Try to run them manually in your terminal to see if they behave the same.


        The issue you are trying to report night already be fixed upstream. Check your current version with `mpm
        --version` and compare it with [the
        changelog](https://kdeldycke.github.io/meta-package-manager/changelog.html).


        You might then try to run the latest development version of `mpm` by:

        - [installing it from its source
        code](https://kdeldycke.github.io/meta-package-manager/development.html#setup-environment)

        - [running the latest binary
        build](https://github.com/kdeldycke/meta-package-manager/actions/workflows/release.yaml?query=branch%3Amain+is%3Asuccess)
        (select the latest `Build & release`/`release.yaml` workflow run and download the binary artifact corresponding
        to your platform and architecture).


        If you still cannot make sense of what happened, or you think `mpm` behavior can be improved, please fill the
        form below and submit it.

  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: "Tell us: 1) what you did, 2) what you expected to happen, and 3) what did happened instead."
      placeholder: Show us what you see!
    validations:
      required: true

  - type: textarea
    id: mpm-config
    attributes:
      label: Meta Package Manager configuration
      description: Provide the current configuration via `mpm --show-params`.
      render: shell-session
      placeholder: mpm --show-params

  - type: textarea
    id: package-manager-list
    attributes:
      label: List package managers
      description: >
        Provide details about identification of package managers by running the
        `mpm --verbosity DEBUG --all-managers managers` command in your terminal.
      render: shell-session
      placeholder: mpm --verbosity DEBUG --all-managers managers

  - type: textarea
    id: mpm-version
    attributes:
      label: Meta Package Manager version
      description: Provide the version you are running and its environment with `mpm --version`.
      render: shell-session
      placeholder: mpm --version
