name: New package manager
description: You would like to see a new package manager supported by `mpm`
labels: ["🎁 feature request"]
body:

  - type: markdown
    attributes:
      value: >
        Before filling this feature request, double check your manager is missing from the [support
        matrix](https://github.com/kdeldycke/meta-package-manager#supported-package-managers-and-operations).


        If you are a developper, you can try to implement support yourself. [Check the contribution
        guide](https://kdeldycke.github.io/meta-package-manager/contributing.html) and propose a Pull Request.


        If you are not a developper, you can still help the project by documenting some of the package manager
        metadata below. And better: if you contibute some raw output of the package manager, the maintainers
        can try a blind implementation of the new manager.

  - type: input
    id: manager-id
    attributes:
      label: ID and name
      description: Either the manager's ID or full name, or better, provides both.
    validations:
      required: true

  - type: input
    id: manager-url
    attributes:
      label: Project URL
      description: Official website or repository in which the package manager is maintained.
    validations:
      required: true

  - type: checkboxes
    id: manager-platforms
    attributes:
      label: Platforms
      description: Platforms supported by the package manager.
      options:
        - label: 🅱️ BSD (FreeBSD, MidnightBSD, NetBSD, OpenBSD, SunOS)
        - label: >-
            🐧 Linux (ALT Linux, Amazon Linux, Android, Arch Linux, Buildroot, CentOS, CloudLinux OS, Debian,
            Exherbo Linux, Fedora, Gentoo Linux, Guix System, IBM PowerKVM, KVM for IBM z Systems, Linux Mint, Mageia,
            Mandriva Linux, Nobara, openSUSE, Oracle Linux, Parallels, Pidora, Raspbian, RedHat Enterprise Linux,
            Rocky Linux, Scientific Linux, Slackware, SUSE Linux Enterprise Server, openSUSE Tumbleweed, Tuxedo OS,
            Ubuntu, Unknown Linux, Windows Subsystem for Linux v1, Windows Subsystem for Linux v2, XenServer)
        - label: 🍎 macOS
        - label: ⨂ Unix (IBM AIX, Cygwin, GNU/Hurd, Solaris)
        - label: 🪟 Windows

  - type: textarea
    id: manager-version
    attributes:
      label: Version
      description: >
        Provides here the command and output that can be used to extract the manager's version.
      render: shell-session
      placeholder: |
        $ pacman --version

           .--.                  Pacman v6.0.1 - libalpm v13.0.1
          / _.-' .-.  .-.  .-.   Copyright (C) 2006-2021 Pacman Development Team
          \  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
           '--'
                              This program may be freely redistributed under
                              the terms of the GNU General Public License.
    validations:
      required: true

  - type: textarea
    id: manager-installed-cmd
    attributes:
      label: Installed command
      description: >
        Command and output to list all packages installed with the manager.
      render: shell-session
      placeholder: |
        $ python -m pip --no-color list --format=json --verbose --quiet | jq
        [
         {
            "version": "1.3",
            "name": "backports.functools-lru-cache",
            "installer": "pip"
          }
        ]

  - type: textarea
    id: manager-outdated-cmd
    attributes:
      label: Outdated command
      description: >
        Command and output to list all installed packages which are outdated.
      render: shell-session
      placeholder: |
        $ brew outdated --json=v2 --formula | jq
        [
          {
            "name": "pygobject3",
            "installed_versions": [
              "3.36.1"
            ],
            "current_version": "3.38.0",
          }
        ]

  - type: textarea
    id: manager-search-cmd
    attributes:
      label: Search command
      description: >
        Command and output to search packages installable with the manager. Provides some variations which allows
        for exact search on package ID, and fuzzy results on package's name and description.
      render: shell-session
      placeholder: |
        $ brew search sed
        ==> Formulae
        gnu-sed ✔                    libxdg-basedir               minised
        ==> Casks
        eclipse-dsl                       marsedit
        google-adwords-editor             prefs-editor

  - type: textarea
    id: manager-install-cmd
    attributes:
      label: Install command
      description: >
        Command and output to install a package. Provides the variation which allows to install a particular version
        of a package.
      render: shell-session
      placeholder: |
        $ python -m pip --no-color install arrow
        Collecting arrow
          Using cached arrow-1.1.1-py3-none-any.whl (60 kB)
        Collecting python-dateutil>=2.7.0
          Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
        Requirement already satisfied: six>=1.5 in python3.9/site-packages (1.16.0)
        Installing collected packages: python-dateutil, arrow
        Successfully installed arrow-1.1.1 python-dateutil-2.8.2

  - type: textarea
    id: manager-upgrade-cmd
    attributes:
      label: Upgrade command
      description: >
        Command and output to upgrade a package. Provides all variations which allows to upgrade only one package or
        all, as well as the CLI targetting one version in particular.
      render: shell-session
      placeholder: |
        $ brew upgrade dupeguru --cask
        ==> Upgrading 1 outdated package:
        dupeguru 4.2.0 -> 4.2.1
        ==> Downloading https://github.com/arsenetar/dupeguru/releases/download/4.2.1/dupeguru_macOS_Qt_4.2.1.zip
        ==> Purging files for version 4.2.0 of Cask dupeguru
        🍺  dupeguru was successfully upgraded!

  - type: textarea
    id: manager-remove-cmd
    attributes:
      label: Remove command
      description: >
        Command and output to remove a package.
      render: shell-session
      placeholder: |
        $ brew uninstall bat
        Uninstalling /usr/local/Cellar/bat/0.21.0... (14 files, 5MB)

  - type: textarea
    id: manager-sync-cmd
    attributes:
      label: Sync command
      description: >
        Command and output to synchronize local metadata from remote repositories.
      render: shell-session
      placeholder: |
        $ sudo apt --quiet --yes update
        Hit:1 http://archive.ubuntu.com xenial InRelease
        Get:2 http://archive.ubuntu.com xenial-updates InRelease [102 kB]
        Get:3 http://archive.ubuntu.com xenial-security InRelease [102 kB]
        Fetched 6,868 kB in 2s (2,680 kB/s)
        Building dependency tree...
        Reading state information...

  - type: textarea
    id: manager-cleanup-cmd
    attributes:
      label: Cleanup command
      description: >
        Command and output to remove all orphaned dependencies, prune left-overs and clear caches.
      render: shell-session
      placeholder: |
        $ yarn cache clean --all
        yarn cache v1.22.19
        success Cleared cache.
        ✨  Done in 0.35s.
