---
name: 🪄 Autofix
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/repomatic/.github/workflows/autofix.yaml@3a04e66e0f653c320bf6e93a8d584f4bf9605a50 # v6.31.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
