---
name: 🪄 Autofix
"on":
  workflow_dispatch:
  schedule:
    - cron: "27 4 * * 1"
  push:
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/repomatic/.github/workflows/autofix.yaml@07e3ef8ae5685c7dfc4af43001b6fc67501396b1 # v7.6.0
    secrets:
      REPOMATIC_NOTIFICATIONS_PAT: ${{ secrets.REPOMATIC_NOTIFICATIONS_PAT }}
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
