---
name: 🪄 Autofix
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/repomatic/.github/workflows/autofix.yaml@9d29583b0b0ca24db08a04e7fe03aa7990e045b5 # v6.23.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
