---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@09b06a00c592eef7f7a3623563e73a443016b3e2 # v6.9.1.dev0
