---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@9314ce774915f19449393a0151c8d44a254f29ca # v6.9.1.dev0
