---
name: 🆙 Changelog & versions
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
    paths:
      - changelog.md
      - "**/pyproject.toml"
      - ".github/workflows/*.yaml"
      - uv.lock
      - "**/*.py"
      - "docs/**"
  workflow_run:
    workflows:
      - "Build & release"
    types:
      - completed
    branches:
      - main

jobs:

  changelog:
    uses: kdeldycke/repomatic/.github/workflows/changelog.yaml@a6458162963b57814a69421fed1f969cbbe1d2b6 # v6.28.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
