---
name: 🆙 Changelog & versions
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
    paths:
      - changelog.md
      - "**/pyproject.toml"
      - ".github/workflows/*.yaml"
      - uv.lock
      - "**/*.py"
      - "docs/**"
  workflow_run:
    workflows:
      - "🚀 Build & release"
    types:
      - completed
    branches:
      - main

jobs:

  changelog:
    uses: kdeldycke/repomatic/.github/workflows/changelog.yaml@2e7b4cd29c6decc9304bc810be03e83844077644 # v7.16.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
