---
name: 🩺 Debug
"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/debug.yaml
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *"

jobs:

  debug:
    uses: kdeldycke/repomatic/.github/workflows/debug.yaml@da519582a030bccb8d204e2ab3f61343e6c349e5 # v6.11.2
