---
name: 🩺 Debug
"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/debug.yaml
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *"

jobs:

  debug:
    uses: kdeldycke/repomatic/.github/workflows/debug.yaml@44d6f69616d5c0c125ce1c35c95b82f4fb6e76e1 # v6.13.0
