---
name: 🩺 Debug
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/debug.yaml
  schedule:
    - cron: "0 12 1 * *"

jobs:

  debug:
    uses: kdeldycke/repomatic/.github/workflows/debug.yaml@6b9586282b103feae63e773c15f788f7d37848bd # v6.29.0
