---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@09b06a00c592eef7f7a3623563e73a443016b3e2 # v6.9.1.dev0
