---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@f600fefb41f28a11f550f43d8145b96438e46b84 # v6.14.0
