---
name: 🏷️ Labels
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release
    types:
      - opened
  issues:
    types:
      - opened

jobs:

  labels:
    uses: kdeldycke/repomatic/.github/workflows/labels.yaml@86620138002b34a18678953b6eb63d09cdc22ce6 # v6.25.1
