---
name: 🏷️ Labels
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release
    types:
      - opened
  issues:
    types:
      - opened

jobs:

  labels:
    uses: kdeldycke/repomatic/.github/workflows/labels.yaml@07e3ef8ae5685c7dfc4af43001b6fc67501396b1 # v7.6.0
