---
name: 🧹 Lint
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.gif"
      - "**/*.jpeg"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.svg"
      - "**/*.webp"
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release

jobs:

  lint:
    uses: kdeldycke/repomatic/.github/workflows/lint.yaml@e8e1f6c651ed0c51dd6622cf316f3f7f591ed3dc # v6.30.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
