---
name: 🧹 Lint
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - prepare-release
      - "renovate/**"

jobs:

  lint:
    uses: kdeldycke/repomatic/.github/workflows/lint.yaml@9314ce774915f19449393a0151c8d44a254f29ca # v6.9.1.dev0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
