---
name: 🧹 Lint
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - prepare-release
      - "renovate/**"

jobs:

  lint:
    uses: kdeldycke/repomatic/.github/workflows/lint.yaml@072c7bbbcdd607011c6ca4fb9d5098532aee2dea # v6.8.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
