---
name: 📈 Forge metrics
"on":
  workflow_dispatch:
  schedule:
    - cron: "41 5 * * 2"

jobs:

  metrics:
    uses: kdeldycke/repomatic/.github/workflows/metrics.yaml@5f78bd26eaacbd5fbe0931b064f30ba61a41ddce # v7.15.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
