---
name: 📈 Forge metrics
"on":
  workflow_dispatch:
  schedule:
    - cron: "41 5 * * 2"

jobs:

  metrics:
    uses: kdeldycke/repomatic/.github/workflows/metrics.yaml@954c819c0e21141997c73f78a2bb7bc8633ed815 # v7.14.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
