---
name: Nix hash
"on":
  workflow_dispatch:

jobs:

  nix-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v31
      - run: >
          nix-prefetch-url
          --unpack
          --type sha256
          "https://github.com/kdeldycke/meta-package-manager/archive/refs/tags/v6.2.1.tar.gz"
      - run: >
          nix hash convert
          --hash-algo sha256
          --to sri
          $(nix-prefetch-url
          --unpack
          --type sha256
          "https://github.com/kdeldycke/meta-package-manager/archive/refs/tags/v6.2.1.tar.gz")
