---
name: 🚀 Build & release
"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  release:
    uses: kdeldycke/repomatic/.github/workflows/release.yaml@9314ce774915f19449393a0151c8d44a254f29ca # v6.9.1.dev0
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
