---
name: 🆕 Renovate
"on":
  workflow_dispatch:
  schedule:
    - cron: "3 17 * * 1"
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yaml
      - renovate.json5

jobs:

  renovate:
    uses: kdeldycke/repomatic/.github/workflows/renovate.yaml@f185b237deb05defc94f8dff02a82a2d9bd579d8 # v6.20.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
