---
name: 🆕 Renovate
"on":
  schedule:
    - cron: "3 17 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yaml
      - renovate.json5

jobs:

  renovate:
    uses: kdeldycke/repomatic/.github/workflows/renovate.yaml@9314ce774915f19449393a0151c8d44a254f29ca # v6.9.1.dev0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
